// pages/api/cron/weekly-digest.js
// Runs every Monday at 8am — sends a weekly summary to all team members
import { createClient } from '@supabase/supabase-js';
import Anthropic from '@anthropic-ai/sdk';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

async function sendWeeklyDigest() {
  await supabase.from('job_logs').insert({
    job_type: 'weekly_digest',
    status: 'started'
  });

  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);

  // Get all teams
  const { data: teams } = await supabase.from('teams').select('id, name');

  for (const team of teams || []) {
    // Get this week's screening results for the team
    const { data: screeningResults } = await supabase
      .from('screening_results')
      .select('*')
      .eq('team_id', team.id)
      .gte('created_at', weekAgo.toISOString())
      .order('created_at', { ascending: false });

    // Get top reports created by team members this week
    const { data: teamUsers } = await supabase
      .from('users')
      .select('id, email, full_name')
      .eq('team_id', team.id);

    const userIds = (teamUsers || []).map(u => u.id);

    const { data: weeklyReports } = userIds.length > 0
      ? await supabase
          .from('reports')
          .select('ticker, analysis, created_at, user_id')
          .in('user_id', userIds)
          .gte('created_at', weekAgo.toISOString())
          .order('created_at', { ascending: false })
          .limit(10)
      : { data: [] };

    if (!teamUsers || teamUsers.length === 0) continue;

    // Generate AI summary of the week
    let weekSummary = '';
    try {
      const summaryPrompt = `
It's Monday morning. Summarize the past week's market themes and provide a forward-looking outlook for the week ahead. Include:
1. Key market movements from last week (major indices, notable sectors)
2. Top 3 themes investors should watch this week
3. Any earnings reports or macro events coming up this week
4. One contrarian or overlooked opportunity for the week

Be concise and actionable. Format with clear sections.
      `.trim();

      const message = await anthropic.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1000,
        messages: [{ role: 'user', content: summaryPrompt }]
      });

      weekSummary = message.content[0].type === 'text' ? message.content[0].text : '';
    } catch (error) {
      console.error('Summary generation error:', error.message);
      weekSummary = 'Weekly market summary unavailable this week.';
    }

    // Build digest content
    const digestContent = buildDigestHTML(team.name, weekSummary, screeningResults, weeklyReports, teamUsers);

    // Queue notification for each team member
    for (const user of teamUsers) {
      await supabase.from('notifications').insert({
        team_id: team.id,
        user_id: user.id,
        type: 'weekly_digest',
        recipient_email: user.email,
        content: digestContent,
        status: 'pending'
      });
    }

    console.log(`Weekly digest queued for team ${team.id} (${teamUsers.length} members)`);
  }

  await supabase.from('job_logs').insert({
    job_type: 'weekly_digest',
    status: 'completed',
    completed_at: new Date()
  });

  return { success: true, timestamp: new Date() };
}

function buildDigestHTML(teamName, summary, screeningResults, reports, users) {
  const week = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const userMap = Object.fromEntries((users || []).map(u => [u.id, u.full_name || u.email]));

  let html = `<h1>📈 Weekly Stock Digest — Week of ${week}</h1>`;
  html += `<p>Team: <strong>${teamName}</strong></p>`;

  html += `<hr><h2>🌍 Market Outlook This Week</h2>`;
  html += `<p>${summary.replace(/\n/g, '<br>')}</p>`;

  if (screeningResults && screeningResults.length > 0) {
    html += `<hr><h2>📋 Daily Screenings This Week (${screeningResults.length})</h2>`;
    html += `<p>Your team ran ${screeningResults.length} automated screenings. Check the app for full details.</p>`;
  }

  if (reports && reports.length > 0) {
    html += `<hr><h2>🔍 Research Reports This Week (${reports.length})</h2>`;
    html += `<ul>`;
    for (const report of reports.slice(0, 5)) {
      const analyst = userMap[report.user_id] || 'Team member';
      const date = new Date(report.created_at).toLocaleDateString();
      html += `<li><strong>${report.ticker}</strong> — analyzed by ${analyst} on ${date}</li>`;
    }
    html += `</ul>`;
    if (reports.length > 5) {
      html += `<p><em>...and ${reports.length - 5} more. See all in the app.</em></p>`;
    }
  }

  html += `<hr><p style="font-size: 12px; color: #6b7280;">Generated by Stock Advisor on ${new Date().toLocaleDateString()}. Log in to see full reports and manage alerts.</p>`;
  return html;
}

export default async function handler(req, res) {
  if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const result = await sendWeeklyDigest();
    return res.status(200).json(result);
  } catch (error) {
    console.error('Weekly digest failed:', error);

    await supabase.from('job_logs').insert({
      job_type: 'weekly_digest',
      status: 'failed',
      error_message: error.message,
      completed_at: new Date()
    }).catch(() => {});

    return res.status(500).json({ error: error.message });
  }
}
